workflows:
  ios-build:
    name: Build .ipa
    environment:
      vars:
        XCODE_WORKSPACE: "MuseStudio.xcworkspace"
        XCODE_SCHEME: "MuseStudio"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.yourcompany.musestudio"  # <-- Replace with real bundle ID
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
      - name: Build .ipa
        script: |
          cd ios
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphoneos
          xcodebuild archive -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -archivePath ../build/$XCODE_SCHEME.xcarchive
          xcodebuild -exportArchive -archivePath ../build/$XCODE_SCHEME.xcarchive -exportOptionsPlist exportOptions.plist -exportPath ../build/ipa
    artifacts:
      - build/ipa/*.ipa
