workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "YourApp.xcworkspace"  # Change this to your actual .xcworkspace filename
        XCODE_SCHEME: "YourApp"                # Change this to your actual scheme name
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build .ipa
        script: |
          xcodebuild clean -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos
          xcodebuild archive -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -archivePath build/$XCODE_SCHEME.xcarchive
          xcodebuild -exportArchive -archivePath build/$XCODE_SCHEME.xcarchive -exportOptionsPlist ios/ExportOptions.plist -exportPath build/ipa
    artifacts:
      - build/ipa/*.ipa
